# Generated by Django 3.1.3 on 2020-11-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMoviesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TopMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('top_movies_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_movie', to='api.topmovieslist')),
            ],
        ),
    ]
