# Generated by Django 3.1.3 on 2020-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovie',
            name='poster_path',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
