# Generated by Django 3.1.3 on 2020-11-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topmovie_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('poster_path', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='TopMoviesList',
            new_name='TopMovies',
        ),
        migrations.DeleteModel(
            name='TopMovie',
        ),
        migrations.AddField(
            model_name='movie',
            name='top_movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='api.topmovies'),
        ),
    ]
