# Generated by Django 3.1.3 on 2020-11-22 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201121_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rank',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
