# Generated by Django 3.1.3 on 2020-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['top_movies', 'rank']},
        ),
        migrations.AddField(
            model_name='topmovies',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
